name: Main Deploy
run-name: Deploying main branch to production.
on: [push]
env:
  AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to S3
        run: aws s3 sync public s3://${{ env.AWS_S3_BUCKET }}
      - name: Clear Cloudfront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ env.AWS_CF_DISTRIBUTION_ID }} --paths /*
